version: '3.8'
services:
  movies:
    image: glpskumar/movies
    ports:
      - "81:80"
  train:
    image: glpskumar/train
    ports:
      - "82:80"
  dth:
    image: glpskumar/dth
    ports:
      - "83:80"
  recharge:
    image: glpskumar/recharge
    ports:
      - "84:80"

